### ISSUE TITLE
ROS-TCP-Connector のバージョンアップに伴う修正について

### ISSUE THREAD

**Issue by devemin** [unity3d-jp/Unity-ROS-MobileRobot-UI-Tutorial#18]
素晴らしい教材をありがとうございます。

こちらを実際に試してみたところでの、一点ご報告させて頂きたいのですが、

当教材は ROS-TCP-Connector の version 0.5.0 前提での説明やコードが実装されておりますが、
ROS-TCP-Connector は現在の最新version が 0.7.0 で、初期化やpub/sub のコードが刷新されているようです。

ですので、新たに当教材を試すときに、0.5.0指定なら正しく動くのですが、0.7.0 を入れてしまってコードが動かずとまどってしまったので、

①　0.5.0 指定で入れないと動かない旨を注記
　または、
②　0.7.0 対応コードに更新

されると、新たなユーザーに良いのかな？とお節介ではありますがここにご報告させて頂きます。
また、0.7.0では、Runtime の Android ビルド（Unity.Robotics.ROSTCPConnectorでのチェックボックス）もデフォルトで有効になっているようです。

参考：
ROS-TCP-Connector 0.7.0 でのチュートリアル
https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/ros_unity_integration/README.md

ただの提案ですので、すぐに close して頂いて構いません。
（私が試した修正でプルリクを出せば良いのでしょうが、素人なので自信が無くすみません💦）

お手数おかけしますが、ご検討いただければ幸いです。
改めて、とてもわかりやすい教材をありがとうございます。

devemin

**Comment by comoc** [comment]
@devemin 様、日頃よりのご利用、並びにissueのご報告いただきありがとうございます。大変助かります。
近日中に0.7.0への更新を予定しています。対応が完了しましたらこちらのチケットの更新にてお知らせいたします。
それまでの間ご不便をおかけしますが、何卒よろしくお願いいたします。

**Comment by devemin** [comment]
@comoc 様

ご丁寧なご返信ありがとうございます。
更新予定とのことで嬉しいです。

いつも Unity は楽しく便利に利用させて頂いております。
今後とも宜しくお願い致します。

devemin

**Comment by comoc** [comment]
@devemin 様 いつもご利用いただきありがとうございます。

mainブランチのHEAD#[c20187a](https://github.com/unity3d-jp/Unity-ROS-MobileRobot-UI-Tutorial/commit/c20187a1d17dabdffd7ca0befde038e9e7ec2ee1)にて、
ROS TCP Connectorの
> ②　0.7.0 対応コードに更新

の件、対応完了いたしました。

ただしAndroid向けのURDF Importerのご利用につきましては、[こちら](https://github.com/Unity-Technologies/ROS-TCP-Connector/issues/266#issuecomment-1081513507)の @Tiryoh さんのコメントおよびコメント中のリンク先の記述にもある通り、今のところ手動でご対応頂く必要がありますので、その点ご留意いただければと思います。

引き続き、どうぞよろしくお願いいたします。
